spring:
  # \u6570\u636E\u6E90\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL8.x \u9A71\u52A8
    url: jdbc:mysql:///jpa?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  # JPA\u914D\u7F6E
  jpa:
    show-sql: true # \u6253\u5370SQL
    hibernate:
      ddl-auto: update # \u6570\u636E\u5E93\u6CA1\u6709\u8868\u65F6\u81EA\u52A8\u6784\u5EFA
    database: mysql  # \u6307\u5B9A\u6570\u636E\u5E93\u7C7B\u578B
    database-platform: org.hibernate.dialect.MySQL8Dialect # \u6570\u636E\u5E93\u65B9\u8A00
